FROM debian:buster

ARG USERNAME=vscode
ARG USER_UID=1000

RUN useradd -m -s /bin/bash -u ${USER_UID} -U ${USERNAME} && \
    mkdir -p /etc/sudoers.d && \
    echo ${USERNAME} ALL=\(ALL\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

RUN apt-get update && \
    apt-get install -y sudo && \
    apt-get install -y git

USER vscode