FROM alpine:3.14

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000

RUN adduser ${USERNAME} -s /bin/sh -D -u ${USER_UID} ${USER_GID} && \
    mkdir -p /etc/sudoers.d && \
    echo ${USERNAME} ALL=\(ALL\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

RUN apk update && \
    apk add sudo && \
    apk add git

USER vscode